services:
  web:
    build: .
    command: gunicorn rapid.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: rapiddb
      POSTGRES_USER: rapiduser
      POSTGRES_PASSWORD: rapidpass

volumes:
  postgres_data:

